//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Task
    {
        public Task()
        {
          
        }
        public int Id { get; set; }
       // public Nullable<int> User { get; set; }
        public string PlanText { get; set; }
        public string ResultText { get; set; }
        public Nullable<double> Time { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public virtual User User { get; set; }
        public virtual Tag Tag { get; set; }

    }
}
